name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.10.1"
          - name: python3.10.1-alpine
            python_version: "3.10.1"
          - name: python3.10.1-alpine3.15
            python_version: "3.10.1"
          - name: python3.10.1-slim
            python_version: "3.10.1"
          - name: python3.10.1
            python_version: "3.10.1"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Dependencies
        run: python3.7 -m pip install docker pytest
      - name: Test Image
        run: bash scripts/test.sh
        env:
          NAME: ${{ matrix.image.name }}
          DOCKERFILE: ${{ matrix.image.dockerfile }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
